### ISSUE TITLE
 Too many open files, unable to open more!  smbd's max open files = 16424

### ISSUE THREAD

**Issue by jgitwhat** [awlx/samba-timemachine#3]
I am getting this error using this container. Is there a parameter I can set to up this to say 500k or something? Any idea how I could get the system limit?

**Comment by awlx** [comment]
You should be able to pass a higher limit with the argument `--ulimit` to docker run.

**Comment by jgitwhat** [comment]
Thanks for responding. I am using portainer to run your image/container. Do you know how I modify within portainer to set the --ulimit?

I apologize I am not very familiar with modifying existing images/containers other than passing env vars through portainer.

I was able to get the below to commands to work, but the setting seems to revert back to defaults after a certain amount of time passes.

docker exec -it timemachine /bin/bash -c "ulimit -n 1048576"

docker exec -it timemachine /bin/bash -c "cat /proc/1/limits"

**Comment by awlx** [comment]
Probably because it wasn't docker which set it at startup.

I am sorry, don't use portainer so I have no idea on how to set it correctly through it :/.

**Comment by jgitwhat** [comment]
Thanks for responding. If anyone knows how to get this working in portainer I will pay $20usd for the solution.

**Comment by bergernetch** [comment]
I am running the container using docker-compose, but use portainer to get an nice overview.

I set the ulimit in my docker-compose.yml like this:

    timemachine:
    image: awlnx/samba-timemachine:latest
    container_name: timemachine
    ports:
      - 10445:445
    volumes:
      - /srv/timemachine/backups:/backups:rw
    restart: unless-stopped
    environment:
      - USER=myuser
      - PASS=mypass
      - USERID=${PUID}
      - GROUPID=${PGID}
      - SHARENAME=Timemachine
      - TMSIZE=3000000
    ulimits:
      nproc: 100000


AFAIK it works, as docker inspect timemachine shows:

    "Ulimits": [
        {   
            "Name": "nproc",
            "Hard": 100000,
            "Soft": 100000
        }
    ],

But portainer does not show anything about ulimits or nproc.
