### ISSUE TITLE
Image is not updating with changes in Alpine or Samba

### ISSUE THREAD

**Issue by delgurth** [awlx/samba-timemachine#6]
This image is for example being used by [ansible-nas](https://github.com/davestephens/ansible-nas), but it has not seen a new version in over 1 year. Alpine Linux has released quite some updates already and also the version of samba provided within this image is now EOL:

https://wiki.samba.org/index.php/Samba_Release_Planning#Current_Stable_Release

Version running in your container: samba-server-4.11.5-r0

I've created a fork to trigger a new build and it now contains: samba-server-4.13.3-r1

Can you please trigger the builds of this image more often? With > 100k downloads, keeping up with new versions of samba seems important.

**Comment by awlx** [comment]
I know because I cannot access my Docker Account anymore and Docker is not at all helpful to recover it.

**Comment by delgurth** [comment]
Ouch :( That sucks. Thanks for your quick reply. Hope you are able to recover the account.

**Comment by awlx** [comment]
<img width="560" alt="Screenshot 2021-03-17 at 11 00 24" src="https://user-images.githubusercontent.com/6527744/111449845-0fd86b00-8710-11eb-977c-70c3a7aeaa5b.png">
I am stuck in this ... and cannot open a ticket because ... I have no associated e-mail address. It's a nightmare.

**Comment by awlx** [comment]
I successfully regained access to my account! Builds are triggered!

**Comment by delgurth** [comment]
Great news. Good to know.
